# -*- coding: utf-8 -*-
"""Employment through COVID

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18BESpVkl9DcomYJSeM2LQ3BIUnfVojnh
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


#import dataset
from google.colab import files

uploaded=files.upload()

df= pd.read_csv("EmploymentAndCovidCLEANED.csv", index_col= 'End_Of_Month', parse_dates=True)
df

import seaborn as sns
import matplotlib.pyplot as plt


sns.kdeplot(x="HOSPITALIZED_COUNT", y="DEATH_COUNT", data=df, fill=True, cmap="Purples_r", cbar=True)
plt.xlabel("Hospitalized Count")
plt.ylabel("Death Count")
plt.title("2D Density Plot for Hospitalizations VS Deaths")

# Show the plot
plt.show()

# create the time series subplots
sns.lineplot(x = "End_Of_Month", y = "Accommodation and Food Services", data = df, label= "Accommodation and Food Services")
sns.lineplot(x = "End_Of_Month", y = "Administrative and Waste Services", data = df, label= "Administrative and Waste Services")
sns.lineplot(x = "End_Of_Month", y = "Arts, Entertainment, and Recreation", data = df, label="Arts, Entertainment, and Recreation")
sns.lineplot(x = "End_Of_Month", y = "Education and Health Services", data = df, label="Education and Health Services")
sns.lineplot(x = "End_Of_Month", y = "Educational Services", data = df, label="Educational Services")
sns.lineplot(x = "End_Of_Month", y = "Employment Services", data = df, label="Employment Services")
sns.lineplot(x = "End_Of_Month", y = "Health Care and Social Assistance", data = df, label="Health Care and Social Assistance")
sns.lineplot(x = "End_Of_Month", y = "Information", data = df, label="Information")
sns.lineplot(x = "End_Of_Month", y = "Leisure and Hospitality", data = df, label="Leisure and Hospitality")
sns.lineplot(x = "End_Of_Month", y = "Management of Companies and Enterprises", data = df, label= "Management of Companies and Enterprises")
sns.lineplot(x = "End_Of_Month", y = "Other Services, except public administration", data = df, label= "Other Services, except public administration")
sns.lineplot(x = "End_Of_Month", y = "Professional and Business Services", data = df, label= "Professional and Business Services")
sns.lineplot(x = "End_Of_Month", y = "Professional, Scientific, and Technical Services", data = df, label= "Professional, Scientific, and Technical Services")
sns.lineplot(x = "End_Of_Month", y = "Real Estate and Rental and Leasing", data = df, label= "Real Estate and Rental and Leasing")
sns.lineplot(x = "End_Of_Month", y = "Trade, Transportation, and Utilities", data = df, label= "Trade, Transportation, and Utilities")
sns.lineplot(x = "End_Of_Month", y = "Transportation and Warehousing", data = df, label= "Transportation and Warehousing")
plt.ylabel("Employment")
plt.xticks(rotation = 15)
plt.legend(bbox_to_anchor=(1, 0.5))
plt.title("Industry Employment Throughout the Pandemic")
plt.savefig('Industry_employment.png',bbox_inches='tight')